# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-17T11:50:21Z"
  labels:
    app: mariadb-pod
  name: mariadb-pod
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "123123"
    image: docker.io/library/mariadb:10
    name: mariadb
    ports:
    - containerPort: 3306
      hostPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mariadb-pvc
  volumes:
  - name: mariadb-pvc
    persistentVolumeClaim:
      claimName: mariadb

