# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.2
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  containers:
  - args:
    - memcached
    image: docker.io/library/memcached:latest
    name: memcached
    ports:
    - containerPort: 11211
      hostPort: 11211
    securityContext: {}

