# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  containers:
  - args:
    - mongod
    image: docker.io/library/mongo:latest
    name: mongodb
    ports:
    - containerPort: 27017
      hostPort: 27017
    volumeMounts:
    - mountPath: /data/configdb
      name: 9818b37cb51858b6e445fe552519a528cbbc5d2dd1964b6fa7949e0508e6b099-pvc
    - mountPath: /data/db
      name: mongodb-pvc
  volumes:
  - name: 9818b37cb51858b6e445fe552519a528cbbc5d2dd1964b6fa7949e0508e6b099-pvc
    persistentVolumeClaim:
      claimName: 9818b37cb51858b6e445fe552519a528cbbc5d2dd1964b6fa7949e0508e6b099
  - name: mongodb-pvc
    persistentVolumeClaim:
      claimName: mongodb
