# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.2

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-19T16:50:37Z"
  labels:
    app: opengist-pod
  name: opengist-pod
spec:
  containers:
  - image: ghcr.io/thomiceli/opengist:1
    name: opengist
    ports:
    - containerPort: 6157
      hostPort: 6157
    volumeMounts:
    - mountPath: /opengist
      name: home-hammurabi-.opengist-host-0
  volumes:
  - hostPath:
      path: /home/hammurabi/.opengist
      type: Directory
    name: home-hammurabi-.opengist-host-0

