# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgresql
  name: postgresql
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: root
    - name: POSTGRES_PASSWORD
      value: "123123"
    image: docker.io/library/postgres:15-alpine
    name: postgresql
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: ce692fab4d130795247a5c102b2b1c0a1b692684f3c21c01c8033addcfca69b8-pvc
  volumes:
  - name: ce692fab4d130795247a5c102b2b1c0a1b692684f3c21c01c8033addcfca69b8-pvc
    persistentVolumeClaim:
      claimName: ce692fab4d130795247a5c102b2b1c0a1b692684f3c21c01c8033addcfca69b8
