# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  containers:
  - args:
    - rabbitmq-server
    image: ghcr.io/hadihammurabi/rabbitmq:latest
    name: rabbitmq
    ports:
    - containerPort: 5672
      hostPort: 5672
    - containerPort: 15672
      hostPort: 15672
    volumeMounts:
    - mountPath: /var/lib/rabbitmq
      name: rabbitmq-pvc
  volumes:
  - name: rabbitmq-pvc
    persistentVolumeClaim:
      claimName: rabbitmq
